genai/client.go, genai/embed.go
=> Document possible model name in docstring

genai/client.go, genai/client_test.go, genai/example_test.go
=> bugfix: nil pointer in joinContent

genai/client_test.go
Add a test that extracts error details.
See #24.
=> add test for error

genai/client.go, genai/client_test.go
=> genai: check for non-empty API key

genai/client.go, genai/client_test.go, genai/config.yaml, genai/content.go, genai/generativelanguagepb_veneer.gen.go
=> genai: support function calling

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Add `bug_report` and `feature_reques`t template. Also route support questions to [Discourse forum](https://discuss.ai.google.dev/).
cc @google/gtech-llm-support
=> Create Github Issue Templates

genai/client.go
=> genai: improve protoveneer instructions and go:generate line

genai/internal/version.go
Once this is submitted I'll tag a new release.
=> genai: increment version

devtools/pre-push-hook.sh, genai/example_test.go
Also, fix an example caught by go vet.
=> devtools/pre-push-hook.sh: add go test and go vet

genai/files.go, genai/files_test.go
=> genai: fix nil pointer converting file metadata

genai/client_test.go
Skip or fix tests to conform to current model behavior.
Skipping the blocking test because I can't find a prompt that
gets blocked.
=> genai: get Live tests to pass

genai/caching.go, genai/caching_test.go, genai/chat.go, genai/client.go, genai/client_test.go, genai/config.yaml, genai/embed.go, genai/generativelanguagepb_veneer.gen.go, genai/internal/generativelanguage/v1beta/generativelanguage-api.json
Add support for CachedContent.
See https://ai.google.dev/gemini-api/docs/caching.
=> genai: add content caching

genai/client.go, genai/client_test.go
Also add a skipped test with a custom http client
=> genai: wrap errors so we can understand where they come from

genai/client.go, genai/client_test.go
Workaround until #151 is fixed
=> genai: make custom HTTP client work again

genai/client_test.go, genai/example_test.go
the model/API are sensitive to our weather example and emit 400s occasionally reuse the movies example from the official docs (https://ai.google.dev/gemini-api/docs/function-calling) instead
Fixes #160
=> genai: fix tool-using example and test

genai/example_test.go, genai/internal/snippets/example_test.go
Aligning with the Python samples per https://github.com/google-gemini/generative-ai-python/pull/459
Main change is in the way output of snippets is marked
=> genai: adjust samples for count tokens

genai/example_test.go
=> genai: add error check to example

genai/client_test.go, genai/testdata/1251.txt
=> genai: add file with 1251 encoding to test error

genai/files.go
=> genai: fix link to MIME types doc

genai/client.go
=> fix: change in string for condition check

README.md
=> Update readme to match other deprecated packages.
