genai/client.go, genai/client_test.go, genai/config.yaml, genai/embed.go, genai/generativelanguagepb_veneer.gen.go, internal/cmd/protoveneer/protoveneer.go
The TaskType is optional.
A separate function is provided for a title.
=> support embeddings

genai/client.go, genai/embed.go
Client.GenerativeModel and Client.EmbeddingModel now accept
both "models/name" and "name".
Remove the GenerativeModel.Name method because it isn't clear
what it should do.
=> accept full name for models

genai/client.go, genai/client_test.go, genai/config.yaml, genai/content.go, genai/example_test.go, genai/generativelanguagepb_veneer.gen.go
Use *float32 for the Temperature field of GenerationConfig.
Provide a SetTemperature method for the user's convenience.
Previously, GenerationConfig.Temperature was a float32 even though
the proto had a *float32, and we intpreted zero as nil. This meant
it was impossible to set a zero temperature: attempting to do
so would transmit a nil Temperature to the server, which the server
would interpret as the default.
No other fields in GenerationConfig have this problem because none
of the others have a valid zero value.
=> bugfix: use a pointer for GenerationConfig.Temperature

genai/client_test.go, genai/config.yaml, genai/embed.go, genai/example_test.go, genai/generativelanguagepb_veneer.gen.go
The API consists of an EmbeddingBatch type to which contents can be added, and then used for the RPC. This is simpler than the alternative API, which would require the user to create a slice of individual requests.
=> implement batch embedding

genai/client.go, genai/client_test.go, genai/embed.go
Add GenerativeModel.Info and EmbeddedModel.Info, which both call the GetModel RPC.
=> genai: support the GetModel RPC

genai/client.go
Provide a way for a user to specify a tuned model to Client.GenerativeModel, so they can use it to generate content.
=> genai: support generation with tuned models

genai/client.go, genai/client_test.go
Previously, the name passed to Client.GenerativeModel was converted to a full model name for the service by prepending "models/" unless that prefix was already present, in which case the name was used unmodified.
For a more general approach, we now treat any name with a slash verbatim, and only prepend "models/" if there is no slash.
=> genai: change construction of full model name

genai/content.go
There's another odd reference in the doc of `Blob`:
```
// Blob contains raw media bytes.
//
// Text should not be sent as raw bytes, use the 'text' field.
```
It's not clear what "the 'text' field" is? 
But this is coming from generated code with protoveneer, so harder to change.
=> Remove stale reference in doc

genai/client.go, genai/client_test.go
NewClient will return an error if not passed the WithAPIKey option.
=> genai: check for API key

CONTRIBUTING.md, genai/client.go, genai/client_test.go, genai/example_test.go
Update tests and examples to use the new preferred names for models.
Currently, GetModel fails on gemini-1.0-pro.
=> genai: use new model names

genai/example_test.go
Now we use GEMINI_API_KEY throughout, not API_KEY
=> examples: align key name env var with new error message

genai/chat.go
Avoid dereferencing a nil.
This may fix an actual bug, but even if it doesn't, it's a good idea to assume as little as possible about values returned from the service.
For #55.
=> genai: check for nil value from service

genai/client.go, genai/client_test.go, genai/config.yaml, genai/content.go, genai/embed.go, genai/generativelanguagepb_veneer.gen.go, genai/list_models.go
Use the v1beta version of the API.
This will provide access to function calling.
=> genai: switch to v1beta

genai/client.go
If the model returns no response, treat that as an error.
Fixes #54.
=> genai: fix panic on nil response

genai/client.go
If any candidate's finish reason is Recitation, return a BlockedError.
Previously, we only did this for a finish reason of Safety.
(Recitation indicates the use of copyrighted material.)
Fixes #61.
=> genai: error on FinishReasonRecitation

genai/client.go
If there is no WithAPIKey option, we were returning an error.
But it's possible that the user provided an alternative HTTP
client that does auth, so don't return an error in that case.
Fixes #80.
=> genai: do not fail with custom HTTP client

genai/example_test.go
SystemInstruction isn't supported by earlier models
=> example: set model for 1.5 for SystemInstruction config

genai/internal/version.go
This CL should be followed by tagging the repo v0.11.2.
=> Update the internal version.

genai/example_test.go
Inspired by #17 
We keep seeing people wanting to be able to use proxies (latest example: https://github.com/eliben/gemini-cli/issues/2), and it's good to have a canonical resource.
It's useful to have an example for this because the interaction of `option.WithHTTPClient` with API keys is tricky (custom HTTP clients don't set the key properly).
=> genai: add example of setting proxy

genai/client.go
Add genai-go/VERSION to the x-goog-api-client header.
Following the Python client, the version is not prefixed with a 'v'.
=> genai: set genai-go in header

genai/client.go
`hasApiKey` checks whether an API or `HTTPClient` is provided, however the check fails when using other auth options.
For example:
`client, err := genai.NewClient(ctx, option.WithTokenSource(ts))`
Results in the following error:
```
You need an API key to use this client.
Visit https://ai.google.dev to get one, put it in an environment variable like GEMINI_API_KEY,
then pass it as an option:
genai.NewClient(ctx, option.WithAPIKey(os.Getenv("GEMINI_API_KEY")))
(If you're doing that already, then maybe the environment variable is empty or unset.)
Import the option package as "google.golang.org/api/option".
```
This PR adds support for additional authentication options to address this limitation.
fixes: #103 
---
Please let me know if you have any suggestions or require further changes :)
=> Check for multiple auth options

genai/client.go
Following #105, a wrong string snuck in
@andersonjoseph FYI
=> genai: fix hasAuthOption check

CONTRIBUTING.md, genai/client_test.go
Requiring flags precludes us from running `go test ./...` in this repository.
The model name is open now so we can just place it as a constant in the file - it's no longer the only model used by the tests either, so it's less confusing. The API key can be provided with an env var like in the examples.
With this change, `go test ./...` now succeeds (the live test skip if the env var key is not set).
Also fix some test expectations to be more resilient.
=> genai: fix live test to not require flags

genai/client_test.go, genai/config.yaml, genai/generativelanguagepb_veneer.gen.go, genai/internal/generativelanguage/v1beta/generativelanguage-api.json, genai/internal/generativelanguage/v1beta/generativelanguage-gen.go, go.mod, go.sum, internal/support/support.go
Add three fields to `File` that are of type time.Time.
This requires the changes to protoveneer in
https://github.com/googleapis/google-cloud-go/pull/10266,
which also includes changes to the support packages.
Running `go generate` also introduced two additional `File` fields,
Error and Metadata, that we will deal with later.
There are also additions to the discovery client which don't concern
us.
=> genai: add File time fields

genai/client.go
Add GenerateContentResponseIterator.MergedResponse, which
returns the merged response.
=> genai: expose the merged response from streaming

genai/client.go
Result: NewClient no longer returns an error if the user
passes option.WithHTTPClient.
=> genai: spell name of HTTP client option correctly

genai/chat.go, genai/client.go, genai/client_test.go, genai/generativelanguagepb_veneer.gen.go, genai/internal/generativelanguage/v1beta/generativelanguage-api.json
Return an error if a conversion fails, instead of panicking.
Currently the only possible such failure is when a FunctionResponse
contains a value that can't be converted to a Struct proto.
=> genai: turn conversion panics to errors

genai/client.go, genai/generate.sh
Use the cached directory for the right version of the pb.go files.
This ensures that the generated code matches the version of
cloud.google.com/go/ai in the go.mod file, rather than whatever
happens to be checked out in the google-cloud-go repo.
=> genai: improve code generation command

genai/caching_test.go, genai/client.go
We weren't passing the cached content name in generation or CountTokens
requests. Fix that.
Also support cached-content token count for CountTokens requests
(not yet implemented in the service).
=> genai: pass cached content in request

genai/client.go, genai/client_test.go, genai/option.go
Add an option that lets Google products identify which calls
are made with this client.
=> genai: add WithAttribution client option

genai/example_test.go, genai/internal/samples/docs-snippets_test.go
We're going to have several more examples that upload files; factor out a function that does this properly, checking for status etc. It's like the function `client_test` uses, but without the `testing.T` scaffold.
=> genai: factor out uploadFile function for examples

genai/caching.go, genai/client.go, genai/debug.go, genai/embed.go, genai/files.go
Sometimes it is useful to see the requests that are being
sent to the service. Add a facility for this.
=> genai: add debug printing of requests

genai/config.yaml, genai/files.go, genai/generativelanguagepb_veneer.gen.go, genai/internal/generativelanguage/v1beta/generativelanguage-api.json
=> genai: improve file upload doc

genai/example_test.go, genai/internal/samples/docs-snippets_test.go
=> genai: generalize uploadFile in examples and add comment

genai/caching_test.go, genai/chat.go, genai/client.go, genai/client_test.go, genai/content.go, genai/embed.go, genai/example_test.go, genai/internal/samples/docs-snippets_test.go
Turns out we already had an internal function like this. The exported one is slightly more ergonomic due to `...`
I tried finding all places where we could benefit form using it
=> genai: add helper function NewUserContent

genai/example_test.go, genai/internal/samples/docs-snippets_test.go
We're requested to add a tool token count example even w/o automatic function calling. Just the function names are sufficient to demonstrate a change in the token count - we don't have to specify schemas
=> genai: add sample for tokens_tools

genai/example_test.go, genai/internal/samples/docs-snippets_test.go
The model seems to require it (even though it correctly infers
that the MIME type is text/plain).
Fixes #198.
=> genai: add explicit MIME type CreateCachedContent example

genai/example_test.go, genai/files.go, genai/internal/samples/docs-snippets_test.go
Sketch for a new convenience method to upload a file from a path. This would let us remove the `uploadFile` helpers from tests and examples. Examples & snippets would all be "inline" without calling out to a function.
=> genai: add convenience client.UploadFileFromPath method

genai/example_test.go, genai/internal/samples/docs-snippets_test.go
Make this match the other language snippets. Tested the change on my machine, and the output is as expected: 
`[{"recipeName": "Chocolate Chip Cookies"}, {"recipeName": "Peanut Butter Cookies"}, {"recipeName": "Oatmeal Raisin Cookies"}, {"recipeName": "Sugar Cookies"}, {"recipeName": "Snickerdoodles"}]`
=> Update prompt in json_no_schema snippet

genai/chat.go, genai/client_test.go
When adding to session history, remove empty text parts.
This is the same change as https://github.com/googleapis/google-cloud-go/pull/10362.
It fixes TestLive/tools/direct.
=> genai: omit empty text parts from session history

.github/workflows/user-input.yml
A new comment on an issue with this label would get the label automatically removed
=> Add a GitHub Action to manage `status: awaiting user response`
